### ISSUE TITLE
error database

### ISSUE THREAD

**Issue by osaaso1** [cmertz11/OpenTraumaRegistry#14]
Hi
I create a sql database then insert the string in aasetting.jason, then Debug->New Instance
after entering username and other info, when I hit Y, this error comes up:
System.ArgumentException: 'Format of the initialization string does not conform to specification starting at index 0.'

Am I doing something wrong?
Best

**Comment by cmertz11** [comment]
Hello,

Apologies, I really need to update the documentation for this.

Did you modify your secrets.json file?  This file is required, but not
included by design in the repo for security purposes.
Essentially, any settings in the secrets file will overwrite matching
settings in the appsettings.json.

Right-Click the OpenTraumaRegistry.Data project and select "Manage User
Secrets".

Mine looks like this:

[image: image.png]

You can set "connectionString" to your connection string and "AESKEY" to
whatever you like.

Let me know if this works for you.

Chris

**Comment by cmertz11** [comment]
The following projects in the solution require entries in the secrets.json file.
OpenTraumaRegistry.Api
OpenTraumaRegistry.Data
OpenTraumaRegistry.UI.MD


Here is how my secrets.json file looks for OpenTraumaRegistry.Data:
![image](https://user-images.githubusercontent.com/5183421/84896325-c0c2b400-b071-11ea-9d60-0c8442477843.png)

**Comment by osaaso1** [comment]
Thanks Chris,
Solved but some issues with New User, such as forcePassReset....
Best

**Comment by cmertz11** [comment]
Ok, in it's current state the application requires an email provider to be configured.  Once a user is created it sends a confirmation email and temp password.  I'm currently making coding changes to introduce a "development" mode which will relax the security restrictions.  I'm hoping to check in the fix in a day or so.

**Comment by osaaso1** [comment]
Sounds great!

**Comment by cmertz11** [comment]
I've checked in the changes.  There is now a new setting "MODE" : "DEVELOPMENT".

**Comment by osaaso1** [comment]
Thanks!
